version: '3.1'

services:
  mariadb:
    container_name: mariadb
    image: mariadb:10.11
    ports:
      - 3311:3306
    environment:
      MARIADB_USER: admin
      MARIADB_PASSWORD: 1111
      MARIADB_ROOT_PASSWORD: 1234
    volumes:
      - /var/lib/mysqld:/var/lib/mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8089:80
    environment:
      - PMA_HOST=mariadb
    depends_on:
      - mariadb
